name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository using git
        uses: actions/checkout@v3
      - name: Install and setup bun package manager
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload build
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
